version: '3.8'

services:
  db:
    image: postgres:16.0
    restart: unless-stopped
    expose:
      - "${DB_PORT}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U ${DB_USER}",
          "-d ${DB_NAME}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s

volumes:
  db-data:
