[autoflake]
recursive = true
remove-all-unused-imports = true
ignore-init-module-imports = true
remove-unused-variables = true
in-place = true

[tool.isort]
profile = "black"
line_length = 79

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | vendor
  | logs
  | upload )/'''
